### PR TITLE
Overlapping partial matches causes a higher than possible match value.

### LINKED ISSUE #5677: list.shouldEndWith fails with IllegalArgumentException
The test below passes in Kotest 6.1.1 and fails in 6.1.2/6.1.3 with _java.lang.IllegalArgumentException: Distance must be between 0 and 1, was: 1.09_:

```kotlin
package test

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.collections.shouldEndWith

class BrokenTest : FreeSpec({
    "should pass" {
        val list = listOf("1.0.0.9/32", "1.0.0.10/32")
        list.shouldEndWith(listOf("1.0.0.10/32"))
    }
})
```

Exception when run with Kotest 6.1.3:
```
Distance must be between 0 and 1, was: 1.09
java.lang.IllegalArgumentException: Distance must be between 0 and 1, was: 1.09
	at io.kotest.assertions.similarity.Distance.<init>(IDistanceCalculator.kt:14)
	at io.kotest.assertions.similarity.StringDistanceCalculatorKt.matchNotNullStrings(StringDistanceCalculator.kt:19)
	at io.kotest.assertions.similarity.VanillaDistanceCalculatorKt.matchNotNull(VanillaDistanceCalculator.kt:14)
	at io.kotest.assertions.similarity.VanillaDistanceCalculator.compare(VanillaDistanceCalculator.kt:6)
	at io.kotest.assertions.similarity.ClosestMatchesKt.closestMatches$lambda$0(ClosestMatches.kt:8)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:243)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:203)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:227)
	at io.kotest.assertions.similarity.ClosestMatchesKt.closestMatches(ClosestMatches.kt:31)
	at io.kotest.assertions.similarity.PossibleMatchesKt.possibleMatchesDescription(PossibleMatches.kt:6)
	at io.kotest.matchers.collections.ContainExactlyKt.appendPossibleMatches(containExactly.kt:211)
	at io.kotest.matchers.collections.StartwithKt.describePartialMatchesInCollection(startwith.kt:76)
	at io.kotest.matchers.collections.StartwithKt$endWith$1.test(startwith.kt:173)
	at io.kotest.matchers.collections.StartwithKt$endWith$1.test(startwith.kt:169)
	at io.kotest.matchers.InvokeMatcherKt.invokeMatcher(InvokeMatcher.kt:10)
	at io.kotest.matchers.ShouldKt.should(should.kt:65)
	at io.kotest.matchers.collections.StartwithKt.shouldEndWith(startwith.kt:155)
	at pl.coretech.cdn.configuration.export.mediacdn.mapper.BrokenTest$1$1.invokeSuspend(BrokenTest.kt:9)
```

### PR DESCRIPTION
**Pull request by Kantis**
Fixed by only including the best partial match for any given range in the expected value.

fixes #5677

### CODE REVIEW

File: kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/assertions/similarity/StringDistanceCalculator.kt [hunk 1]
```diff
@@ -38,7 +38,20 @@ internal fun ratioOfPartialMatchesInString(
...
    val maxLength = listOf(expected, actual).maxOf { it.length }
-   val numberOfMatchedCharacters = partialMatches.sumOf { it.length }
+   val numberOfMatchedCharacters = partialMatches.filterOverlapping().sumOf { it.length }
    return BigDecimal.valueOf(numberOfMatchedCharacters.toLong())
       .divide(BigDecimal.valueOf(maxLength.toLong()), 2, RoundingMode.HALF_DOWN)
 }
+
+// In case of overlapping partial matches, we eliminate the overlapping ones and only include the longest match
+// for any given slice of the expected collection.
+private fun List<PartialCollectionMatch>.filterOverlapping(): List<PartialCollectionMatch> {
```
Comment (AlexCue987) [inline kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/assertions/similarity/StringDistanceCalculator.kt:48]: would it make sense to make this function `internal` and unit test it explicitly?

**Review by AlexCue987 — APPROVED** [review]
we'll add tests in the next PR
