### PR TITLE
Improve JS execution to use common spec executor and fix after project listeners

### LINKED ISSUE #5423: Support Kotlin/JS vol. 2
Hi Team!

I'm aware of kotest/kotest#5468 but I think it was closed prematurely. For me, the lack of gutter icons and in fact any IDE integration is a major pain point. I'm close to moving back to kotlin.test and leaving just kotest assertions library.

Implementation-wise, my intuition tells me that, contrary to what was suggested in the closed ticket, the individual tests can be detected by static analysis - no need to execute it. IntelliJ plugins API probably exposes some kind of AST or [PSI](https://plugins.jetbrains.com/docs/intellij/psi.html) that would be helpful in detecting e.g. invocations of `test` function inside `FunSpec`.

### LINKED ISSUE #5607: After project listener not executed on JS
**Which version of Kotest are you using**

### PR DESCRIPTION
**Pull request by sksamuel**
Updates JS execution to use the same spec executors as native and JVM.
Fixes issues with coroutines delaying output which causes test names to disappear.

Fixes #5423
Fixes #5607

### CODE REVIEW

File: kotest-runner/kotest-runner-junit-platform/src/jvmMain/kotlin/io/kotest/runner/junit/platform/KotestJunitPlatformTestEngine.kt [hunk 1]
```diff
@@ -164,3 +166,4 @@ class KotestJunitPlatformTestEngine : TestEngine {
    }
 }
 
+internal class MultipleExceptions(val causes: List<Throwable>) : Exception(causes.first())
```
Comment (alfonsoristorato) [inline kotest-runner/kotest-runner-junit-platform/src/jvmMain/kotlin/io/kotest/runner/junit/platform/KotestJunitPlatformTestEngine.kt]: we are not using this

**Review by alfonsoristorato — APPROVED** [review]

File: kotest-runner/kotest-runner-junit-platform/src/jvmMain/kotlin/io/kotest/runner/junit/platform/KotestJunitPlatformTestEngine.kt (hunk 1 above)
Comment (sksamuel) [reply kotest-runner/kotest-runner-junit-platform/src/jvmMain/kotlin/io/kotest/runner/junit/platform/KotestJunitPlatformTestEngine.kt]: good spot, removed
