### PR TITLE
Fixed beforeSpec in concurrency.

### LINKED ISSUE #5040: Tests don't wait on `beforeSpec` completion when using `Concurrent` mode in Kotest 6.0.1
After updating to Kotest 6.0.1 my tests no longer wait until `beforeSpec` finishes execution.

Test case:
```kotlin
@OptIn(ExperimentalKotest::class)
class ParallelTestsInSpec : StringSpec(), PrepareSpecListener {

    override suspend fun beforeSpec(spec: Spec) {
        println("> beforeSpec start")
        runBlocking {
            for (i in 1..2) {
                async {
                    // some long operation, e.g. network call
                    delay(1000)
                    println("  task $i done")
                }
            }
        }
        println("> beforeSpec end")
    }

    override suspend fun afterSpec(spec: Spec) = println("> afterSpec")

    init {
        testExecutionMode = TestExecutionMode.Concurrent
        // Kotest 5.9.1 used:
        // concurrency = 10

        "test 1" { println("- test 1") }
        "test 2" { println("- test 2") }
    }
```

Expected output, and output in Kotest 5.9.1:
```
> beforeSpec start
  task 1 done
  task 2 done
> beforeSpec end
- test 1
- test 2
> afterSpec
```

Actual output in Kotest 6.0.1:
```
> beforeSpec start
- test 2
  task 1 done
  task 2 done
> beforeSpec end
- test 1
> afterSpec
```

### PR DESCRIPTION
**Pull request by sksamuel**
Move test enabled checks into the spec execution phase to avoid state tracking complications.

This is a big one, but I've simplified the spec execution pipelines a lot, it's just touched a lot of files to get there.

Fixes #5040

### CODE REVIEW

File: kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/core/spec/style/scopes/StringSpecRootScope.kt [hunk 1]
```diff
@@ -87,8 +87,6 @@ interface StringSpecRootScope : RootScope {
 /**
  * This scope exists purely to stop nested string scopes.
  */
-
-
```
Comment (alfonsoristorato) [inline kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/core/spec/style/scopes/StringSpecRootScope.kt:91]: I left this space there by mistake, just curiosity, do you use a formatter that I should also be using when I push PRs?

File: kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/listener/CollectingTestEngineListener.kt [hunk 2]
```diff
@@ -65,6 +65,8 @@ class CollectingTestEngineListener : AbstractTestEngineListener(), Mutex by Mute
    fun TestCase.toKey(): TestCaseKey {
       return TestCaseKey(this.descriptor, this.name, this.spec::class)
    }
+
+   fun testResult(name: String): TestResult = tests.toList().first { it.first.name.name == name }.second
```
Comment (alfonsoristorato) [inline kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/listener/CollectingTestEngineListener.kt]: if you like 😄 
```suggestion
   fun testResult(name: String): TestResult =  tests.entries.first { it.key.name.name == name }.value
```

**Review by alfonsoristorato — COMMENTED** [review]
looks solid, but it's quite big so happy to leave it for another reviewer to approve to avoid the auto-merge

File: kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/core/spec/style/scopes/StringSpecRootScope.kt (hunk 1 above)
Comment (sksamuel) [reply kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/core/spec/style/scopes/StringSpecRootScope.kt:91]: no I just noticed myself I guess
