### PR TITLE
Remove unnecessary delay when retry and fix error message

### LINKED ISSUE #3890: retry has unnecessary delay
**Which version of Kotest are you using**
5.8.0

The [retry](https://github.com/kotest/kotest/blob/01bd98ff10102c51b5a80b51fb375c68264f627d/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/Retry.kt#L63) function is like this:

```
while (end.hasNotPassedNow() && retrySoFar < config.maxRetry) {
    ...
      retrySoFar++
      delay(nextAwaitDuration)
      nextAwaitDuration *= config.multiplier
}
```

This causes `retry` to make one more `delay` than is necessary. It would make tests faster (i.e. not unnecessarily slower) if we exit early using `break` or with an `if`:

```
while (end.hasNotPassedNow() && retrySoFar < config.maxRetry) {
    ...
    retrySoFar++
    if (end.hasNotPassedNow() && retrySoFar < config.maxRetry) {
        delay(nextAwaitDuration)
        nextAwaitDuration *= config.multiplier
    }
}
```

### PR DESCRIPTION
**Pull request by kshired**
resolve #3890

Pre-check the number of retries to eliminate additional delays

### CODE REVIEW

File: kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/Retry.kt [hunk 1]
```diff
@@ -85,6 +85,7 @@ suspend fun <T> retry(
          // else ignore and continue
       }
       retrySoFar++
+      if (retrySoFar >= config.maxRetry) break
```
Comment (klitoskyriacou) [inline kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/Retry.kt]: Why only checking `retrySoFar`? It could also be that the end time has passed, even if fewer than max retries have been taken.

Comment (klitoskyriacou) [reply kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/Retry.kt]: Also note the failure message is misleading: `Test failed after ${config.delay.toLong(DurationUnit.SECONDS)} seconds`. Here, `delay` is only the initial delay. It ignores the multiplier, and it ignores how many times we've delayed.

Comment (kshired) [reply kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/Retry.kt]: @klitoskyriacou 

Thank you for review. I've revised code to reflect your code review.

**Review by klitoskyriacou — APPROVED** [review]

**Review by klitoskyriacou — APPROVED** [review]

**Review by Kantis — APPROVED** [review]
