### PR TITLE
fix: Nested scopes do not share a test scheduler, #4318

### LINKED ISSUE #4318: Nested scopes do not share a test scheduler
Following test:

```kotlin
class DispatchersTest : WordSpec(
    {
        coroutineTestScope = true
        isolationMode = IsolationMode.InstancePerLeaf

        "a" should {
            println("Scheduler in a: $testCoroutineScheduler")
            "b" {
                println("Scheduler in b: $testCoroutineScheduler")
            }
        }
    },
)

```

Will print out:

```
Scheduler in a: kotlinx.coroutines.test.TestCoroutineScheduler@22d0639b
Scheduler in b: kotlinx.coroutines.test.TestCoroutineScheduler@4229d48d
```

Note that every block has a different coroutine scheduler.

In a practical sense, this means that nested scopes do not share virtual time, which could weak havoc, if you want to control the time:

```kotlin
class DispatchersTest : WordSpec(
    {
        coroutineTestScope = true
        isolationMode = IsolationMode.InstancePerLeaf

        "a" should {
            println("time before delay: ${testCoroutineScheduler.currentTime}")

            delay(1_000)

            println("time after delay but before b: ${testCoroutineScheduler.currentTime}")

            "b" {
                println("time in b: ${testCoroutineScheduler.currentTime}")
            }
        }
    },
)
```

will print

```
time before delay: 0
time after delay but before b: 1000
time in b: 0
```

Note that the time has reset to 0, even though code should just execute sequentially from a to the nested b.

This is essentially a reopen of the https://github.com/kotest/kotest/issues/3238, it looks like the fix was not complete.

**Which version of Kotest are you using** 5.6.1

### PR DESCRIPTION
**Pull request by pientaa**
Fixes #4318

### CODE REVIEW

File: kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/io/kotest/engine/DispatchersSharedCoroutineSchedulerTest.kt [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+import io.kotest.matchers.shouldBe
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.delay
+
+@OptIn(ExperimentalCoroutinesApi::class)
+class DispatchersSharedCoroutineSchedulerTest : WordSpec({
+   coroutineTestScope = true
+   isolationMode = IsolationMode.InstancePerLeaf
+
+   "a" should {
```
Comment (AlexCue987) [inline kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/io/kotest/engine/DispatchersSharedCoroutineSchedulerTest.kt]: should we replace `"a"` and `"b"`  with  more descriptive test names?

Comment (pientaa) [reply kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/io/kotest/engine/DispatchersSharedCoroutineSchedulerTest.kt]: sure

**Review by AlexCue987 — APPROVED** [review]

**Comment by matejdro** [comment]
Any chance of a release with this fix included, @sksamuel? Thanks.
