### PR TITLE
Use the original failure when ErrorCollector contains single failure

### LINKED ISSUE #3236: throw AssertionFailedError when shouldBe is the only failure in the assertSoftly block
When just using `shouldBe`:

```kotlin
val longStringA = "sjdigjiosgoidfguiohdfispdjgpiodjgiosdjgiosdjoijsdiogjsdiogjsdiojgiosdjgiosdjgiojsdoigjsdoigjisodjgoisdjgiosdjgoisdjoijgoisjg"
val longStringB = "sjdigjiosgoidfguiohdfispdjgpiodjgiosdjgiosdjoijsdiogjsdiogjsdiojgiosdjgxosdjgiojsdoigjsdoigjisodjgoisdjgiosdjgoisdjoijgoisjg"

longStringA shouldBe longStringB
```

kotest throws AssertionFailedError, which generates a nice "Click to see difference" button in IntelliJ:

image

However, when that same assert is wrapped with `assertSoftly`:

```kotlin
val longStringA = "sjdigjiosgoidfguiohdfispdjgpiodjgiosdjgiosdjoijsdiogjsdiogjsdiojgiosdjgiosdjgiojsdoigjsdoigjisodjgoisdjgiosdjgoisdjoijgoisjg"
val longStringB = "sjdigjiosgoidfguiohdfispdjgpiodjgiosdjgiosdjoijsdiogjsdiogjsdiojgiosdjgxosdjgiojsdoigjsdoigjisodjgoisdjgiosdjgoisdjoijgoisjg"
                
assertSoftly {
    // Assume more assertions here that pass

    longStringA shouldBe longStringB
}
```

kotest throws just regular plain AssertionError, which does not generate "Click to see difference":

image

I realize that this is normal when there are multiple exceptions, because AssertionFailedError can only cover one comparison. But if assertSoftly's only failure is `shouldBe` assertion, it would be really nice if it threw AssertionFailedError to get the "Click to see difference" button to show.

### PR DESCRIPTION
**Pull request by Kantis**
fixes #3236 

`AssertionFailedError` is JVM-specific, so had to move some stuff to expect/actuals.

### CODE REVIEW

**Review by myuwono — APPROVED** [review]

File: kotest-assertions/kotest-assertions-shared/src/jvmTest/kotlin/com/sksamuel/kotest/ErrorCollectorTests.kt [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package com.sksamuel.kotest
+
+import io.kotest.assertions.AssertionFailedError
+import io.kotest.assertions.assertSoftly
+import io.kotest.assertions.throwables.shouldThrow
+import io.kotest.core.spec.style.FreeSpec
+import io.kotest.matchers.should
+import io.kotest.matchers.shouldBe
+
+class ErrorCollectorTests : FreeSpec(
```
Comment (myuwono) [inline kotest-assertions/kotest-assertions-shared/src/jvmTest/kotlin/com/sksamuel/kotest/ErrorCollectorTests.kt:10]: ah right there's no module for jsTest..

File: kotest-assertions/kotest-assertions-shared/src/desktopMain/kotlin/io/kotest/assertions/ErrorCollector.kt [hunk 2]
```diff
@@ -1,6 +1,23 @@
...
+import io.kotest.mpp.stacktraces
 import kotlin.native.concurrent.SharedImmutable
 
 @SharedImmutable
 actual val errorCollector: ErrorCollector = NoopErrorCollector
+
+actual fun ErrorCollector.collectiveError(): AssertionError? {
+   val failures = errors()
+   clear()
+   return if (failures.isNotEmpty()) {
```
Comment (matejdro) [inline kotest-assertions/kotest-assertions-shared/src/desktopMain/kotlin/io/kotest/assertions/ErrorCollector.kt]: Could this be written cleaner as a when or else if statement instead of nested if?

**Review by matejdro — APPROVED** [review]
Tested on my local machine and it seems to work fine. Made a comment for minor readability improvement.

File: kotest-assertions/kotest-assertions-shared/src/desktopMain/kotlin/io/kotest/assertions/ErrorCollector.kt (hunk 2 above)
Comment (Kantis) [reply kotest-assertions/kotest-assertions-shared/src/desktopMain/kotlin/io/kotest/assertions/ErrorCollector.kt]: It could, yeah.. I'll do that.

File: kotest-assertions/kotest-assertions-shared/src/jvmTest/kotlin/com/sksamuel/kotest/ErrorCollectorTests.kt (hunk 1 above)
Comment (Kantis) [reply kotest-assertions/kotest-assertions-shared/src/jvmTest/kotlin/com/sksamuel/kotest/ErrorCollectorTests.kt:10]: Not sure what you meant with this 🤪  Did you mean that we should add a `jsTest` to check that I didn't break the js/desktop error collector?

File: kotest-assertions/kotest-assertions-shared/src/desktopMain/kotlin/io/kotest/assertions/ErrorCollector.kt (hunk 2 above)
Comment (Kantis) [reply kotest-assertions/kotest-assertions-shared/src/desktopMain/kotlin/io/kotest/assertions/ErrorCollector.kt]: Done :)
