### PR TITLE
Fixing Arb.localDate when minDate == maxDate

### LINKED ISSUE #3829: LocalDate generator fails if minDate and maxDate are equal
When using the `localDate` generator, the following exception occurs if `minDate` and `maxDate` are equal:

```
Random range is empty: [0, 0).
java.lang.IllegalArgumentException: Random range is empty: [0, 0).
[... stack trace]
```

The exception comes from the code here:

https://github.com/kotest/kotest/blob/ce6b4feddf5364f3c6a9992d086c5229c50b046d/kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt#L64C5-L64C5

A minimal example to reproduce the bug:

```kotlin
class BugExample : DescribeSpec({
  val failingGenerator : Arb<LocalDate> = Arb.localDate(minDate = LocalDate.MIN, maxDate = LocalDate.MIN)
  describe("The above generator") {
    it("Fails") {
      forAll(failingGenerator) { true }
    }
  }
})
```

And a more concrete example of real-world code that can make this happen, when the date generated by the first generator is equal to the default `minDate` :

```kotlin
class BugExample2 : DescribeSpec({
  val orderedDatesGenerator: Arb<Pair<LocalDate, LocalDate>> =
    Arb.localDate().flatMap { laterDate: LocalDate -> Arb.localDate(maxDate = laterDate).map { earlierDate -> Pair(earlierDate, laterDate) } }
  describe("The above generator") {
    it("sometimes fails, if laterDate is the default minDate") {
      forAll(failingGenerator) { true }
    }
  }
})
```

I'm not completely sure what the best way to address this is. Maybe before calling random, check if the range is empty and in that case return a constant ?

### PR DESCRIPTION
**Pull request by Kantis**
Now simply returns a constant Arb for the given date.

Fixes #3829

### CODE REVIEW

**Review by myuwono — APPROVED** [review]

File: kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt [hunk 1]
```diff
@@ -56,6 +56,7 @@ fun Arb.Companion.localDate(
    minDate: LocalDate = LocalDate.of(1970, 1, 1),
    maxDate: LocalDate = LocalDate.of(2030, 12, 31)
 ): Arb<LocalDate> {
+   if (minDate == maxDate) return Arb.constant(minDate)
```
Comment (myuwono) [inline kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt]: Also i just realised maybe we should require maxdate >= mindate to fail early..
