### PR TITLE
Resolve #1387. Catch all exceptions in project listeners.

### LINKED ISSUE #1387: Before\AfterProject catch only one Exception
[This](https://github.com/kotest/kotest/blob/master/kotest-core/src/jvmMain/kotlin/io/kotest/core/engine/KotestEngine.kt#L98), [this](https://github.com/kotest/kotest/blob/master/kotest-core/src/jvmMain/kotlin/io/kotest/core/engine/KotestEngine.kt#L108), [this](https://github.com/kotest/kotest/blob/master/kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt#L19) and [this](https://github.com/kotest/kotest/blob/master/kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt#L27)
work and handle only for first exception in `afterProject` and `beforeProject` callbacks.
In `kotest-tests-core` and other projects I can register several callbacks and I want to have guarantee that all of them will be invoked and if callback has some assertions I will be notified about all exceptions during my test run because test run may take hours (for example Selenium tests).
I did with `afterProject` callbacks by myself but with `beforeProject` can't without big changes of code.

### PR DESCRIPTION
**Pull request by crazyk2**
Add listener name as part of #1388
Welcome to discuss

### CODE REVIEW

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt [hunk 1]
```diff
@@ -13,22 +13,41 @@ import io.kotest.core.test.TestResult
 import io.kotest.fp.Try
 import io.kotest.mpp.log
 
+
+fun List<ProjectListener>.resolveName() =
```
Comment (sksamuel) [inline kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt:17]: A better name might be groupByName()

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt [hunk 2]
```diff
@@ -13,22 +13,41 @@ import io.kotest.core.test.TestResult
...
-fun List<Listener>.afterProject(): Try<Unit> = Try {
-   log("invokeAfterAll")
-   filterIsInstance<ProjectListener>().forEach { it.afterProject() }
-}.mapFailure { AfterProjectListenerException(it) }
+fun List<Listener>.afterProject(): Try<List<RuntimeException>> = Try {
+   log("invokeAfterProject")
+   filterIsInstance<ProjectListener>()
+      .resolveName()
+      .map { it.first to Try { it.second.afterProject() } }
+      .filter { it.second.isFailure() }
```
Comment (sksamuel) [inline kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt:34]: Please add a method to Try.kt called collectFailures, which does the filter and map for you in a more elegant way.

`fun List<Try<A>>.collectFailures()`

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt [hunk 3]
```diff
@@ -13,22 +13,41 @@ import io.kotest.core.test.TestResult
...
+      .map { AfterProjectListenerException(it.first, (it.second as Try.Failure).error) }
+}.mapFailure { AfterProjectListenerException("afterProjectsInvocation", it) }
 
 /**
  * Invokes the beforeProject listeners, and prints project config using [dumpProjectConfig].
  */
-fun List<Listener>.beforeProject() = Try {
-   log("invokeBeforeAll")
+fun List<Listener>.beforeProject(): Try<List<RuntimeException>> = Try {
```
Comment (sksamuel) [inline kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt]: Should this return be Try<list<BeforeProjectListenerException>> ?

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt [hunk 4]
```diff
@@ -13,22 +13,41 @@ import io.kotest.core.test.TestResult
...
+      }
+
 /**
  * Invokes any afterProject functions from the given listeners.
  */
-fun List<Listener>.afterProject(): Try<Unit> = Try {
-   log("invokeAfterAll")
-   filterIsInstance<ProjectListener>().forEach { it.afterProject() }
-}.mapFailure { AfterProjectListenerException(it) }
+fun List<Listener>.afterProject(): Try<List<RuntimeException>> = Try {
```
Comment (sksamuel) [inline kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt]: Should this return value by Try<List<AfterProjectListenerException>>

File: kotest-extensions/kotest-extensions-allure/src/jvmMain/kotlin/io/kotest/extensions/allure/AllureTestListener.kt [hunk 5]
```diff
@@ -28,6 +28,9 @@ fun TestCase.description() = spec::class.findAnnotation<io.qameta.allure.Descrip
 @AutoScan
 object AllureTestListener : TestListener, ProjectListener {
 
+   override val name: String
+      get() = "AllureTestListener"
```
Comment (sksamuel) [inline kotest-extensions/kotest-extensions-allure/src/jvmMain/kotlin/io/kotest/extensions/allure/AllureTestListener.kt]: We can do this without the get() ?

**Review by sksamuel — CHANGES_REQUESTED** [review]
This is awesome.

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt (hunk 1 above)
Comment (crazyk2) [reply kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt:17]: grouping is only first step. And why this step is needed. JUnit can't register dynamic test with the same name if you has several equaled listener names you should add some different part to name. This is why it called resolveName or make listeners name to be differrent

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt (hunk 3 above)
Comment (crazyk2) [reply kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt]: I don't understand question but try to answer. Earlier beforeProject return just `Try` and don't use success result of it only failed result. It works only until first error. Now we wrap each before\after call with each own `Try` and filter only Failed results because Success results are not interested for us. So return should be only List of exception of known type. 
And Kotlin compiler doesn't allow to use just list without type `Try<List>` 
image

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt (hunk 4 above)
Comment (crazyk2) [reply kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt]: Answered above

File: kotest-extensions/kotest-extensions-allure/src/jvmMain/kotlin/io/kotest/extensions/allure/AllureTestListener.kt (hunk 5 above)
Comment (crazyk2) [reply kotest-extensions/kotest-extensions-allure/src/jvmMain/kotlin/io/kotest/extensions/allure/AllureTestListener.kt]: Definitely

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt (hunk 2 above)
Comment (crazyk2) [reply kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt:34]: To be honest I don't know how to do it.
If you could do refactoring it it would be nice

File: kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt (hunk 3 above)
Comment (sksamuel) [reply kotest-core/src/commonMain/kotlin/io/kotest/core/runtime/callbacks.kt]: Github hid some of the message because of the < > tags. I was asking if the return type should be List of AfterProjectListenerException rather than List of RuntimeException

**Comment by sksamuel** [comment]
> You delete my dependency. I used it

Add it back in.
