### PR TITLE
Avoid afterEvaluate in KotestPlugin

### LINKED ISSUE #5733: Kotlin/Native broken with 6.1.4
The way KSP works, registering processors in `afterEvaluate` is too late and results in the KSP tasks being skipped ([reported by Zac Sweers two years ago](https://github.com/google/ksp/issues/1789) and closed as fixed, but is still happening).

In Kotest 6.1.4 the whole Gradle plugin execution got wrapped in `afterEvaluate`. Kotest 6.1.3 works as long as the KSP plugin is applied before the Kotest one.

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #5733

### CODE REVIEW

File: kotest-framework/kotest-framework-plugin-gradle/src/main/kotlin/io/kotest/framework/gradle/KotestPlugin.kt [hunk 1]
```diff
@@ -111,33 +107,31 @@ abstract class KotestPlugin : Plugin<Project> {
...
+            )
          }
       }
    }
 
-   private fun configureAlwaysRerun(project: Project) {
+   private fun configureAlwaysRerun(project: Project, alwaysRerunTests: Property<Boolean>) {
       project.tasks.withType(AbstractTestTask::class.java).configureEach {
-         outputs.upToDateWhen { false }
+         outputs.upToDateWhen { !alwaysRerunTests.get() }
```
Comment (alfonsoristorato) [inline kotest-framework/kotest-framework-plugin-gradle/src/main/kotlin/io/kotest/framework/gradle/KotestPlugin.kt]: this will throw if we don't use a default, how about `.getOrElse(false)`?

Comment (sksamuel) [reply kotest-framework/kotest-framework-plugin-gradle/src/main/kotlin/io/kotest/framework/gradle/KotestPlugin.kt]: Ok makes sense.

**Review by alfonsoristorato — APPROVED** [review]
