### PR TITLE
Include private specs by default #3915

### LINKED ISSUE #3879: Private Test Classes
JUnit supports execution of private Kotlin test classes. For some reason IntelliJ dropped support for that, although it supported it in the past. 😝 The Kotest IntelliJ plugin supports private Kotlin test classes (all the necessary gutter icons are drawn), but Kotest with the JUnit runner fails. It complains that it cannot find any tests with that name.

Now, this could be a bug report for the Kotest IntelliJ plugin, just asking for not drawing the gutter icons when the class is private. Like IntelliJ does it since a while for JUnit. I'm not asking for that, because I believe that test classes should be private. They shouldn't show up in auto-completion, and they shouldn't be reusable.

### PR DESCRIPTION
**Pull request by sksamuel**
This is a breaking change. In 5.x private classes were excluded.
The system property and config option allows users to revert to this behavior.

Closes #3879

### CODE REVIEW

File: kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/config/applyConfigFromAbstractProjectConfig.kt [hunk 1]
```diff
@@ -42,6 +42,7 @@ internal fun applyConfigFromProjectConfig(config: AbstractProjectConfig, configu
    // discovery
    config.discoveryClasspathFallbackEnabled?.let { configuration.discoveryClasspathFallbackEnabled = it }
    config.disableTestNestedJarScanning?.let { configuration.disableTestNestedJarScanning = it }
+   config.includePrivateClasses?.let { configuration.ignorePrivateClasses = it }
```
Comment (LeoColman) [inline kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/config/applyConfigFromAbstractProjectConfig.kt]: Include vs ignore

I think at some point it got inverted

Comment (sksamuel) [reply kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/config/applyConfigFromAbstractProjectConfig.kt]: Thanks.

File: kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/ClassVisibilitySpecRefInterceptor.kt [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+         ref.kclass.visibility == KVisibility.PRIVATE && !allowPrivate() -> Result.success(emptyMap())
+         else -> fn(ref)
+      }
+   }
+
+   /**
+    * We allow private classes if the configuration flag or system property to ignore is set to true.
+    */
+   private fun allowPrivate(): Boolean {
+      return context.configuration.ignorePrivateClasses ||
```
Comment (LeoColman) [inline kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/ClassVisibilitySpecRefInterceptor.kt:30]: Ignore seems inverted here too

Comment (sksamuel) [reply kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/ClassVisibilitySpecRefInterceptor.kt:30]: I've gone with ignorePrivateClasses in this revision.
Since include is now the default.
Just pushed some changes + test.

File: kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt [hunk 3]
```diff
@@ -297,6 +297,12 @@ abstract class AbstractProjectConfig {
    @ExperimentalKotest
    open var testCoroutineDispatcher: Boolean = Defaults.testCoroutineDispatcher
 
+   /**
+    * If set to false then private spec classes will be ignored by the test engine.
+    * Defaults to true.
+    */
+   open var ignorePrivateClasses: Boolean? = null
```
Comment (LeoColman) [inline kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt:303]: Can it really be null if we are saying the default is true?

Comment (LeoColman) [reply kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt:303]: I also assume the default is false now

**Review by LeoColman — APPROVED** [review]

File: kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt (hunk 3 above)
Comment (sksamuel) [reply kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt:303]: yep fixed

**Comment by OliverO2** [comment]
Will private classes be discovered on native targets?

**Comment by sksamuel** [comment]
> Will private classes be discovered on native targets?

No, that's determined by the compiler plugin, not the runtime lookup that the JVM uses.

**Comment by OliverO2** [comment]
A cursory look shows that the plugin actually does detect private specs so with this PR we should have consistency between targets.

I wonder if we should switch JVM discovery to the compiler plugin as well and have it all in one place, and fast.

**Comment by sksamuel** [comment]
I'm going to see how we do this with the new kotest gradle plugin. At the moment, we rely on gradle to supply the list of test classes. Still experimenting. In master now, there is no more classgraph though which is nice.
