### PR TITLE
Fix #4306 - fixes the order of `expected` and `but was` outout in `containAll`

### LINKED ISSUE #4306: `shouldContainAll` -> is the output of `expected` and `but was`  incorrectly swapped?
Kotest version `5.9.1`

Is the output of `expected` and `but was` in the `shouldContainAll` check incorrectly swapped?

```kotlin
priceSettings.priceModifiersWoodType shouldContainAll priceSettingsDto.priceModifiersWoodType.map {
        it.toModel()
      }
```

```
Collection should contain all of [PriceModifierWoodType(value=10.0099999999999997868371792719699442386627197265625, woodType=ASH), PriceModifierWoodType(value=20.00, woodType=OAK)] but was missing [PriceModifierWoodType(value=10.0099999999999997868371792719699442386627197265625, woodType=ASH)]Possible matches:
java.lang.AssertionError: Collection should contain all of [PriceModifierWoodType(value=10.0099999999999997868371792719699442386627197265625, woodType=ASH), PriceModifierWoodType(value=20.00, woodType=OAK)] but was missing [PriceModifierWoodType(value=10.0099999999999997868371792719699442386627197265625, woodType=ASH)]Possible matches:
 expected: PriceModifierWoodType(value=10.01, woodType=ASH),
  but was: PriceModifierWoodType(value=10.0099999999999997868371792719699442386627197265625, woodType=ASH),
```

the `value=10.0099999999..` is in `priceSettingsDto`. The `priceSettings` is the one, which is tested.

If it is a mistake I am willing to look for the bug and create a PR with a fix.

### PR DESCRIPTION
**Pull request by mrclrchtr**
Fixes #4306 

But I think I have uncovered another bug with the fix:

The test “print one possible match for one mismatched element” should be successful in my opinion, right? Currently it fails.

Context:
```kotlin
         "print one possible match for one mismatched element" {
            shouldThrowAny {
               listOf(sweetGreenPear, sweetGreenApple, sourYellowLemon).shouldContainAll(
                  listOf(sweetGreenPear, sweetRedApple)
               )
            }.shouldHaveMessage("""
               |Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
               | expected: Fruit(name=apple, color=red, taste=sweet),
               |  but was: Fruit(name=apple, color=green, taste=sweet),
               |  The following fields did not match:
               |    "color" expected: <"red">, but was: <"green">
    """.trimMargin())
         }
```

Log:
```
io.kotest.assertions.AssertionFailedError: Throwable should have message:
"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
    "color" expected: <"red">, but was: <"green">"

Actual was:
"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=pear, color=green, taste=sweet),
  The following fields did not match:
    "name" expected: <"apple">, but was: <"pear">
        "color" expected: <"red">, but was: <"green">

 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
    "color" expected: <"red">, but was: <"green">"

expected:<"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
    "color" expected: <"red">, but was: <"green">"> but was:<"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=pear, color=green, taste=sweet),
  The following fields did not match:
    "name" expected: <"apple">, but was: <"pear">
        "color" expected: <"red">, but was: <"green">

 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
    "color" expected: <"red">, but was: <"green">">
	at com.sksamuel.kotest.matchers.collections.ShouldContainAllTest$1$5.invokeSuspend(ShouldContainAllTest.kt:128)
```

I think the first entry in both lists should be successfully found and matched. The second entry is the one that should not fit. Right?

### CODE REVIEW

**Comment by AlexCue987** [comment]
> Fixes #4306
> 
> But I think I have uncovered another bug with the fix:
> 
> The test “print one possible match for one mismatched element” should be successful in my opinion, right? Currently it fails.
> 
> Context:
> 
> ```kotlin
>          "print one possible match for one mismatched element" {
>             shouldThrowAny {
>                listOf(sweetGreenPear, sweetGreenApple, sourYellowLemon).shouldContainAll(
>                   listOf(sweetGreenPear, sweetRedApple)
>                )
>             }.shouldHaveMessage("""
>                |Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
>                | expected: Fruit(name=apple, color=red, taste=sweet),
>                |  but was: Fruit(name=apple, color=green, taste=sweet),
>                |  The following fields did not match:
>                |    "color" expected: <"red">, but was: <"green">
>     """.trimMargin())
>          }
> ```
> 
> Log:
> 
> ```
> io.kotest.assertions.AssertionFailedError: Throwable should have message:
> "Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=apple, color=green, taste=sweet),
>   The following fields did not match:
>     "color" expected: <"red">, but was: <"green">"
> 
> Actual was:
> "Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=pear, color=green, taste=sweet),
>   The following fields did not match:
>     "name" expected: <"apple">, but was: <"pear">
>         "color" expected: <"red">, but was: <"green">
> 
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=apple, color=green, taste=sweet),
>   The following fields did not match:
>     "color" expected: <"red">, but was: <"green">"
> 
> expected:<"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=apple, color=green, taste=sweet),
>   The following fields did not match:
>     "color" expected: <"red">, but was: <"green">"> but was:<"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=pear, color=green, taste=sweet),
>   The following fields did not match:
>     "name" expected: <"apple">, but was: <"pear">
>         "color" expected: <"red">, but was: <"green">
> 
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=apple, color=green, taste=sweet),
>   The following fields did not match:
>     "color" expected: <"red">, but was: <"green">">
> 	at com.sksamuel.kotest.matchers.collections.ShouldContainAllTest$1$5.invokeSuspend(ShouldContainAllTest.kt:128)
> ```
> 
> I think the first entry in both lists should be successfully found and matched. The second entry is the one that should not fit. Right?

Correct. Expected should be `sweetRedApple` and actual should be `sweetGreenApple`, and currently this test expects it the other way around. Can you fix this test too?

**Comment by mrclrchtr** [comment]
I think you misunderstood me. I have adapted the test and am of the opinion that the error message should be as shown in the code example above. 

`sweetGreenPear` should be the first entry. It should be found and matched, right? 

The second entry in `actual` is `sweetGreenApple`. But we are looking for `sweetRedApple`. So the error message should be the following:

```
expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
     "color" expected: <"red">, but was: <"green">
```

But the error message is however (as can be seen in the log in the `actual` part):
```
Actual was:
"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=pear, color=green, taste=sweet),
  The following fields did not match:
    "name" expected: <"apple">, but was: <"pear">
        "color" expected: <"red">, but was: <"green">
```

Or am I wrong? Should the order not matter?

If I'm right, I might also find the time for this fix.
But the question would then be whether the test should be disabled first in order to be able to merge this PR?

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt [hunk 1]
```diff
@@ -140,15 +140,15 @@ class ShouldContainAllTest : WordSpec() {
                   listOf(sweetGreenApple, sourYellowLemon)
                )
             }.message.shouldEndWith("""
-               | expected: Fruit(name=apple, color=red, taste=sweet),
-               |  but was: Fruit(name=apple, color=green, taste=sweet),
+               | expected: Fruit(name=apple, color=green, taste=sweet),
+               |  but was: Fruit(name=apple, color=red, taste=sweet),
```
Comment (AlexCue987) [inline kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt:150]: these changes make sense to me

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt [hunk 2]
```diff
@@ -122,15 +122,15 @@ class ShouldContainAllTest : WordSpec() {
 
          "print one possible match for one mismatched element" {
             shouldThrowAny {
-               listOf(sweetGreenApple, sweetGreenPear, sourYellowLemon).shouldContainAll(
-                  listOf(sweetGreenApple, sweetRedApple)
+               listOf(sweetGreenPear, sweetGreenApple, sourYellowLemon).shouldContainAll(
+                  listOf(sweetGreenPear, sweetRedApple)
```
Comment (AlexCue987) [inline kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt]: Unfortunately, here both the assertion and the expected output have both changed, which ,makes it more difficult to review. Can you revert just the assertion back to 
```kotlin
 shouldThrowAny {
               listOf(sweetGreenApple, sweetGreenPear, sourYellowLemon).shouldContainAll(
                  listOf(sweetGreenApple, sweetRedApple)
```
so that the only this that changes is the expected message? The changes on lines 143 and 144 are very easy to review.

**Review by AlexCue987 — CHANGES_REQUESTED** [review]
LGTM, and thank you for fixing this, but can we accomplish the same result with less changes?

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt (hunk 2 above)
Comment (mrclrchtr) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt]: Ok, I have now adjusted the test so that it runs successfully and only output has been adjusted. Does the name “print one possible match for one mismatched element” still make sense now?

Comment (mrclrchtr) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt]: There are actually two differences. That was also the reason why I adjusted the assertion to have only one difference to the exception. This in turn caused the problem I described above!

Comment (AlexCue987) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt]: > There are actually two differences. That was also the reason why I adjusted the assertion to have only one difference to the exception. This in turn caused the problem I described above!

Now I understand why you made that change to the assertion itself, and I do agree that your change is an improvement. Yes, let's have the assertion as you originally suggested, because it's a much cleaner test:
```
istOf(sweetGreenPear, sweetGreenApple, sourYellowLemon).shouldContainAll(
                  listOf(sweetGreenPear, sweetRedApple)
```

So sorry about this misunderstanding.

Comment (mrclrchtr) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt]: Thank you for your quick answers!

> So sorry about this misunderstanding.

No problem at all.

But unfortunately it's not enough to rewrite the test. This is the second part I have described. 
If one use

```kotlin
listOf(sweetGreenPear, sweetGreenApple, sourYellowLemon).shouldContainAll(
                  listOf(sweetGreenPear, sweetRedApple)
```

then the result is:

```
Actual was:
"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=pear, color=green, taste=sweet),
  The following fields did not match:
    "name" expected: <"apple">, but was: <"pear">
        "color" expected: <"red">, but was: <"green">

 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
    "color" expected: <"red">, but was: <"green">"
```

And that seems to be wrong or not? The first one (`but was: Fruit(name=pear, color=green, taste=sweet)`) shouldn't show up, should it?

And if it should, why is `sourYellowLemon` not displayed?

Comment (AlexCue987) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainAllTest.kt]: > Thank you for your quick answers!
> 
> > So sorry about this misunderstanding.
> 
> No problem at all.
> 
> But unfortunately it's not enough to rewrite the test. This is the second part I have described. If one use
> 
> ```kotlin
> listOf(sweetGreenPear, sweetGreenApple, sourYellowLemon).shouldContainAll(
>                   listOf(sweetGreenPear, sweetRedApple)
> ```
> 
> then the result is:
> 
> ```
> Actual was:
> "Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=pear, color=green, taste=sweet),
>   The following fields did not match:
>     "name" expected: <"apple">, but was: <"pear">
>         "color" expected: <"red">, but was: <"green">
> 
>  expected: Fruit(name=apple, color=red, taste=sweet),
>   but was: Fruit(name=apple, color=green, taste=sweet),
>   The following fields did not match:
>     "color" expected: <"red">, but was: <"green">"
> ```
> 
> And that seems to be wrong or not? The first one (`but was: Fruit(name=pear, color=green, taste=sweet)`) shouldn't show up, should it?
> 
> And if it should, why is `sourYellowLemon` not displayed?

I concur, `sweetGreenPear` should not show up, as it matches only on one field, so it's just noise - this is an issue we should fix. But this issue is unrelated to your change, which (your change) makes sense and should be merged.

I'll take care of the issue with `sweetGreenPear` in the output, so that the output will be only

```kotlin
"Collection should contain all of [Fruit(name=pear, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)] but was missing [Fruit(name=apple, color=red, taste=sweet)]Possible matches:
 expected: Fruit(name=apple, color=red, taste=sweet),
  but was: Fruit(name=apple, color=green, taste=sweet),
  The following fields did not match:
    "color" expected: <"red">, but was: <"green">"
```

but that will be in a separate PR , later. let's merge this PR as is, and fix this test later.

**Review by AlexCue987 — APPROVED** [review]

**Comment by AlexCue987** [comment]
TY for the fix, @mrclrchtr

**Comment by mrclrchtr** [comment]
Thank you, too.
