### PR TITLE
fix gradle include combinator

### LINKED ISSUE #3277: Gradle filters should be additive
**Which version of Kotest are you using**
5.5.3

# Context
All tests from A* and B* were skipped instead of being ran. 
```
gradle test --tests "A*" --tests "B*"
```

This was a regression from 5.4.x, where this used to work. This was because kotest 5.5.3 were using the wrong combinators for combining the inclusion filters.

### PR DESCRIPTION
**Pull request by myuwono**
fixes #3277

### CODE REVIEW

File: kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/gradle/GradleClassMethodRegexTestFilter.kt [hunk 1]
```diff
@@ -14,7 +14,7 @@ class GradleClassMethodRegexTestFilter(private val patterns: List<String>) : Tes
       logger.log { Pair(descriptor.toString(), "Testing against $patterns") }
       return when {
          patterns.isEmpty() -> TestFilterResult.Include
-         patterns.all { match(it, descriptor) } -> TestFilterResult.Include
+         patterns.any { match(it, descriptor) } -> TestFilterResult.Include
```
Comment (myuwono) [inline kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/gradle/GradleClassMethodRegexTestFilter.kt:17]: this was the bug

**Review by Kantis — APPROVED** [review]

File: kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/gradle/GradleClassMethodRegexTestFilter.kt (hunk 1 above)
Comment (Kantis) [reply kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/gradle/GradleClassMethodRegexTestFilter.kt:17]: @myuwono do you want to get a patch release out, or should we put the fix in 5.6?

Comment (myuwono) [reply kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/gradle/GradleClassMethodRegexTestFilter.kt:17]: I reckon it's good to get this out as a patch version.
