### PR TITLE
Fix coroutines probe dump with background coroutines

### LINKED ISSUE #4058: Foreground coroutines are not waited for by the test when debug probes are enabled, in the root spec
**Which version of Kotest are you using**
5.9.0

Normally, kotlinx-coroutines-test awaits all foreground coroutines before ending the test.

### Example 1

```kotlin
class ForegroundTest1 : FunSpec({
	this.coroutineTestScope = true
	this.coroutineDebugProbes = false

	test("Start foreground task") {
		launch {
			delay(1000)
			println("In a foreground scope")
		}
		println("In the test body")
	}
})
```

Output:
```
In the test body
In a foreground scope
```

This is the expected behavior. The test body finished, then awaited foreground coroutines.

### Example 2

```kotlin
class ForegroundTest2 : FunSpec({
	this.coroutineTestScope = true
	this.coroutineDebugProbes = true

	test("Start foreground task") {
		launch {
			delay(1000)
			println("In a foreground scope")
		}
		println("In the test body")
	}
})
```

Output:
```
In the test body
Coroutines dump 2024/06/03 20:33:44

Coroutine "coroutine#15":StandaloneCoroutine{Active}@6d071712, state: CREATED
	at _COROUTINE._CREATION._(CoroutineDebugging.kt:30)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:161)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
```

This is incorrect behavior: the test should have waited for all foreground tasks to run before terminating. The output should be exactly the same as the first example.

The same problem is observed with `StringSpec`. I did not test the other specs.

### Example 3

Interestingly enough, this bug does not appear in nested tests.

```kotlin
class ForegroundTest3 : FunSpec({

	context("Without debug probes") {
		coroutineTestScope = true
		coroutineDebugProbes = false

		test("Start foreground task") {
			launch {
				delay(1000)
				println("In a foreground scope")
			}
			println("In the test body")
		}
	}

	context("With debug probes") {
		coroutineTestScope = true
		coroutineDebugProbes = true

		test("Start foreground task") {
			launch {
				delay(1000)
				println("In a foreground scope")
			}
			println("In the test body")
		}
	}
})
```

Output:
```
In the test body
In a foreground scope

In the test body
In a foreground scope
```

This made it particularly difficult to track down :sweat_smile: I hope that helps you find the cause, somehow.

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #4058 

Coroutine probe dump should happen after the tests and launched coroutines have completed. We can do this by moving the probe interceptor to be invoked sooner.

### CODE REVIEW

**Review by LeoColman — APPROVED** [review]

File: kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/coroutines/CoroutineDebugTest.kt [hunk 1]
```diff
@@ -27,10 +31,54 @@ class CoroutineDebugTest : FunSpec() {
...
                .withProjectConfig(p)
+               .withoutEnvFilters()
                .execute()
                .errors.shouldBeEmpty()
          }
-         output shouldContain "DeferredCoroutine"
+         output shouldContain "Coroutines dump"
+      }
+
+      // https://github.com/kotest/kotest/issues/4058
```
Comment (LeoColman) [inline kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/coroutines/CoroutineDebugTest.kt:41]: I like tests for specific issues

Comment (sksamuel) [reply kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/coroutines/CoroutineDebugTest.kt:41]: Yeah me too
