### PR TITLE
Add lazy clue and fix some windows test failures

### LINKED ISSUE #1766: Variation of clue / asClue to accept lazy
**Please describe the feature you'd like to see including any solutions in mind if you have any**

### PR DESCRIPTION
**Pull request by jschneidereit**
Fixes #1766

Created PR to get feedback since I also included some fixes for tests that fail under certain conditions in windows.

### CODE REVIEW

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/file/FileMatchersTest.kt [hunk 1]
```diff
@@ -45,14 +45,13 @@ import io.kotest.matchers.shouldBe
 import io.kotest.matchers.shouldNot
 import io.kotest.matchers.string.shouldEndWith
 import io.kotest.matchers.string.shouldMatch
+import sun.font.FontUtilities.isWindows
```
Comment (jschneidereit) [inline kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/file/FileMatchersTest.kt]: Fix me

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/file/FileMatchersTest.kt [hunk 2]
```diff
@@ -278,3 +277,18 @@ class FileMatchersTest : FunSpec() {
     }
   }
 }
+
+private fun isNotWindowsOrIsWindowsElevated(isWindows: Boolean): Boolean {
```
Comment (jschneidereit) [inline kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/file/FileMatchersTest.kt]: I can get rid of this if it's "too much" but it was easy enough to make

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/assertions/ClueTest.kt [hunk 3]
```diff
@@ -7,8 +7,11 @@ import io.kotest.assertions.withClue
 import io.kotest.core.spec.style.FreeSpec
 import io.kotest.matchers.Matcher
 import io.kotest.matchers.MatcherResult
+import io.kotest.matchers.nulls.shouldBeNull
 import io.kotest.matchers.shouldBe
 import io.kotest.matchers.string.shouldContain
+import io.kotest.matchers.string.shouldStartWith
+import java.util.*
```
Comment (jschneidereit) [inline kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/assertions/ClueTest.kt:14]: My first time using IJ on this box, I'll fix this setting if this is undesirable

File: kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/launcher/TeamCityConsoleReporterTest.kt [hunk 4]
```diff
@@ -24,6 +26,13 @@ import io.kotest.matchers.string.shouldHaveLineCount
 import io.kotest.matchers.string.shouldStartWith
 import kotlin.reflect.KClass
 
+private val osName = System.getProperty("os.name").toLowerCase()
+
+class EnabledIfNotWindows : EnabledCondition {
+   override fun enabled(specKlass: KClass<out Spec>): Boolean = osName.contains("windows")
+}
+
+@EnabledIf(EnabledIfNotWindows::class)
```
Comment (jschneidereit) [inline kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/launcher/TeamCityConsoleReporterTest.kt]: Now that I think about this more, the leading and trailing `\r` might be due to the clue invocation, but I'm not sure. I'll come back to this one.

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/assertions/ClueTest.kt (hunk 3 above)
Comment (sksamuel) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/assertions/ClueTest.kt:14]: I do prefer to not have * but on java.util. it's not too bad.

File: kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/file/FileMatchersTest.kt (hunk 1 above)
Comment (sksamuel) [reply kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/file/FileMatchersTest.kt]: This might be useful https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/SystemUtils.html

File: kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/ErrorCollector.kt [hunk 5]
```diff
@@ -29,38 +29,38 @@ interface ErrorCollector {
     */
    fun clear()
 
-   fun pushClue(clue: Any)
+   fun pushClue(clue: () -> String)
```
Comment (sksamuel) [inline kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/ErrorCollector.kt]: I think we could probably turn ErrorCollector into an internal class.

File: kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/clues.kt [hunk 6]
```diff
@@ -20,7 +37,7 @@ inline fun <R> withClue(clue: Any, thunk: () -> R): R {
  */
 inline fun <T : Any, R> T.asClue(block: (T) -> R): R {
    try {
-      errorCollector.pushClue(this)
+      errorCollector.pushClue { this.toString() }
```
Comment (sksamuel) [inline kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/clues.kt]: could probably just delegate this entire method to the other withClue

inline fun <T : Any, R> T.asClue(block: (T) -> R): R = withClue(lazy { this.toString() }, block)

**Review by sksamuel — APPROVED** [review]

File: kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/ErrorCollector.kt (hunk 5 above)
Comment (jschneidereit) [reply kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/ErrorCollector.kt]: Same with the interface?

**Review by sksamuel — APPROVED** [review]
